<?php

namespace Proxies\__CG__\HRETA\EntidadesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Proyecto extends \HRETA\EntidadesBundle\Entity\Proyecto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setVersion($version)
    {
        $this->__load();
        return parent::setVersion($version);
    }

    public function getVersion()
    {
        $this->__load();
        return parent::getVersion();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function addIdu(\HRETA\EntidadesBundle\Entity\Usuario $idus)
    {
        $this->__load();
        return parent::addIdu($idus);
    }

    public function removeIdu(\HRETA\EntidadesBundle\Entity\Usuario $idus)
    {
        $this->__load();
        return parent::removeIdu($idus);
    }

    public function getIdus()
    {
        $this->__load();
        return parent::getIdus();
    }

    public function setIdtipo(\HRETA\EntidadesBundle\Entity\TipoProyecto $idtipo = NULL)
    {
        $this->__load();
        return parent::setIdtipo($idtipo);
    }

    public function getIdtipo()
    {
        $this->__load();
        return parent::getIdtipo();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getIdexped()
    {
        $this->__load();
        return parent::getIdexped();
    }

    public function setIdexped(\HRETA\EntidadesBundle\Entity\ExpedienteArquitectura $idexped = NULL)
    {
        $this->__load();
        return parent::setIdexped($idexped);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'version', 'descripcion', 'idus', 'idtipo', 'idexped');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}