<?php

namespace Proxies\__CG__\HRETA\EntidadesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TipoProyecto extends \HRETA\EntidadesBundle\Entity\TipoProyecto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDenominacion($denominacion)
    {
        $this->__load();
        return parent::setDenominacion($denominacion);
    }

    public function getDenominacion()
    {
        $this->__load();
        return parent::getDenominacion();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addProyecto(\HRETA\EntidadesBundle\Entity\Proyecto $proyectos)
    {
        $this->__load();
        return parent::addProyecto($proyectos);
    }

    public function removeProyecto(\HRETA\EntidadesBundle\Entity\Proyecto $proyectos)
    {
        $this->__load();
        return parent::removeProyecto($proyectos);
    }

    public function getProyectos()
    {
        $this->__load();
        return parent::getProyectos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'denominacion', 'proyectos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}