security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            
            logout:       
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/admin/, role: ROLE_ADMIN }       
        - { path: ^/rtfarquitectura/.*/edit, role: ROLE_ADMIN }
        - { path: ^/rtfarquitectura/.*/delete, role: ROLE_ADMIN }
        - { path: ^/rtfarquitectura/new, role: ROLE_ADMIN }
        
        - { path: ^/expedientearquitectura/.*/edit, role: ROLE_ADMIN }
        - { path: ^/expedientearquitectura/.*/delete, role: ROLE_ADMIN }
        - { path: ^/expedientearquitectura/new, role: ROLE_ADMIN }
        
        - { path: ^/proyecto/.*/edit, role: ROLE_ADMIN }
        - { path: ^/proyecto/.*/delete, role: ROLE_ADMIN }
        - { path: ^/proyecto/new, role: ROLE_ADMIN }
        - { path: ^/usuario, role: ROLE_ADMIN }
        
        
    
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN