
    
expedientearquitectura:
    pattern:  /
    defaults: { _controller: "EntidadesBundle:ExpedienteArquitectura:index" }

expedientearquitectura_show:
    pattern:  /{id}/show
    defaults: { _controller: "EntidadesBundle:ExpedienteArquitectura:show" }

expedientearquitectura_new:
    pattern:  /new
    defaults: { _controller: "EntidadesBundle:ExpedienteArquitectura:new" }

expedientearquitectura_create:
    pattern:  /create
    defaults: { _controller: "EntidadesBundle:ExpedienteArquitectura:create" }
    requirements: { _method: post }

expedientearquitectura_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EntidadesBundle:ExpedienteArquitectura:edit" }

expedientearquitectura_update:
    pattern:  /{id}/update
    defaults: { _controller: "EntidadesBundle:ExpedienteArquitectura:update" }
    requirements: { _method: post|put }

expedientearquitectura_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EntidadesBundle:ExpedienteArquitectura:delete" }
    requirements: { _method: post|delete }
