<?php

namespace HRETA\EntidadesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RtfArquitecturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RtfArquitecturaRepository extends EntityRepository
{
}
